<?php

// $Id: xoops_version.php,v 1.4 2007/04/27 18:58:35 andrew Exp $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <https://www.xoops.org>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //

// Any copyright notice, instructions, etc...
$modversion['name'] = _MI_AMCONTACT_NAME;
$modversion['version'] = 0.05;
$modversion['description'] = _MI_AMCONTACT_DESC;
$modversion['credits'] = '';
$modversion['author'] = 'Andrew Mills';
$modversion['help'] = 'help.html';
$modversion['license'] = 'GPL see LICENSE.txt';
$modversion['official'] = 0;
$modversion['image'] = 'modulelogo.png';
$modversion['dirname'] = 'amcontact';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Menu
$modversion['hasMain'] = 1;

// Templates
$modversion['templates'][1]['file'] = 'amcont_index.html';
$modversion['templates'][1]['description'] = 'Main index';

// Blocks
#$modversion['blocks'][1]['file']		= "articles_latest.php";
#$modversion['blocks'][1]['name']		= _MI_ARTICLES_BNAME1;
#$modversion['blocks'][1]['description']	= "Shows latest articles";
#$modversion['blocks'][1]['show_func']	= "articles_latest_show";
#$modversion['blocks'][1]['edit_func']   = "articles_latest_edit";
#$modversion['blocks'][1]['options']     = "5|18";
#$modversion['blocks'][1]['template']	= "articles_block_latest.html";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'amcont_questions';

// Config options
$k = 1;
// Must be logged in to send.
$modversion['config'][$k]['name'] = 'loggedin';
$modversion['config'][$k]['title'] = '_MI_AMCONT_LOGGEDIN';
$modversion['config'][$k]['description'] = '_MI_AMCONT_LOGGEDINDSC';
$modversion['config'][$k]['formtype'] = 'yesno';
$modversion['config'][$k]['valuetype'] = 'int';
$modversion['config'][$k]['default'] = 0;

// Maximum allowed user characters in message.
$k++;
$modversion['config'][$k]['name'] = 'maxchars';
$modversion['config'][$k]['title'] = '_MI_AMCONT_MAXCHARS';
$modversion['config'][$k]['description'] = '_MI_AMCONT_MAXCHARSDSC';
$modversion['config'][$k]['formtype'] = 'textbox';
$modversion['config'][$k]['valuetype'] = 'int';
$modversion['config'][$k]['default'] = 1000;

// Template for e-mail.
$k++;
$modversion['config'][$k]['name'] = 'bodytemplate';
$modversion['config'][$k]['title'] = '_MI_AMCONT_BDYTMPLT';
$modversion['config'][$k]['description'] = '_MI_AMCONT_BDYTMPLTDSC';
$modversion['config'][$k]['formtype'] = 'textarea';
$modversion['config'][$k]['valuetype'] = 'text';
$modversion['config'][$k]['default'] = _MI_AMCONT_BDYTMPLTTXT;

// Default name - username or realname
$k++;
$modversion['config'][$k]['name'] = 'defaultname';
$modversion['config'][$k]['title'] = '_MI_AMCONT_DEFNAME';
$modversion['config'][$k]['description'] = '_MI_AMCONT_DEFNAMEDSC';
$modversion['config'][$k]['formtype'] = 'select';
$modversion['config'][$k]['valuetype'] = 'int';
$modversion['config'][$k]['default'] = '0';
$modversion['config'][$k]['options'] = ['_MI_AMCONT_DEFNAME_OPT_0' => '0', '_MI_AMCONT_DEFNAME_OPT_1' => '1'];

// Type of verification to use.
$k++;
$modversion['config'][$k]['name'] = 'verifytype';
$modversion['config'][$k]['title'] = '_MI_AMCONT_VERTYPE';
$modversion['config'][$k]['description'] = '_MI_AMCONT_VERTYPEDSC';
$modversion['config'][$k]['formtype'] = 'select';
$modversion['config'][$k]['valuetype'] = 'int';
$modversion['config'][$k]['default'] = '0';
$modversion['config'][$k]['options'] = ['_MI_AMCONT_VERTYPE_OPT_0' => '0', '_MI_AMCONT_VERTYPE_OPT_1' => '1', '_MI_AMCONT_VERTYPE_OPT_2' => '2'];

// Width for message text box.
$k++;
$modversion['config'][$k]['name'] = 'textboxwidth';
$modversion['config'][$k]['title'] = '_MI_AMCONT_TBOXWIDTH';
$modversion['config'][$k]['description'] = '_MI_AMCONT_TBOXWIDTHDSC';
$modversion['config'][$k]['formtype'] = 'textbox';
$modversion['config'][$k]['valuetype'] = 'int';
$modversion['config'][$k]['default'] = 30;

// Height for message text box.
$k++;
$modversion['config'][$k]['name'] = 'textboxheight';
$modversion['config'][$k]['title'] = '_MI_AMCONT_TBOXHEIGHT';
$modversion['config'][$k]['description'] = '_MI_AMCONT_TBOXHEIGHTDSC';
$modversion['config'][$k]['formtype'] = 'textbox';
$modversion['config'][$k]['valuetype'] = 'int';
$modversion['config'][$k]['default'] = 10;

// Intro text
$k++;
$modversion['config'][$k]['name'] = 'introtext';
$modversion['config'][$k]['title'] = '_MI_AMCONT_INTROTEXT';
$modversion['config'][$k]['description'] = '_MI_AMCONT_INTROTEXTDSC';
$modversion['config'][$k]['formtype'] = 'textarea';
$modversion['config'][$k]['valuetype'] = 'text';
$modversion['config'][$k]['default'] = _MI_AMCONT_INTROTEXTTXT;
